version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/app_dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: npm run dev
volumes:
  db_data:
